package ComponentesSwing;

import java.awt.Color;
import java.awt.Font;
import javax.swing.*;

/**
 * A simple login alert frame with improved aesthetics.
 *
 * @author Matias
 */
public class FrmAvisoLogin extends javax.swing.JFrame {

    /**
     * Creates a new FrmAvisoLogin.
     *
     * @param msg The message to display in the alert.
     */
    public FrmAvisoLogin(String msg) {
        initComponents();
        jLabel1.setText(msg);
    }

    /**
     * This method initializes the components of the frame.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aviso");
        setBackground(new java.awt.Color(240, 248, 255));

        // Configure label
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 18));
        jLabel1.setForeground(Color.DARK_GRAY);
        jLabel1.setText("AVISO");

        // Configure button
        jButton1.setText("OK");
        jButton1.setBackground(new Color(50, 150, 250));
        jButton1.setForeground(Color.WHITE);
        jButton1.setFont(new Font("Segoe UI", Font.BOLD, 14));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(evt -> dispose());

        // Layout
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null); // Center the frame on screen
    }// </editor-fold>

    /**
     * The main method to run the FrmAvisoLogin frame.
     *
     * @param args Command line arguments.
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            String msg = "This is a sample message!";
            new FrmAvisoLogin(msg).setVisible(true);
        });
    }

    // Variables declaration
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}
