package ComponentesSwing;

import uy.ctc.edu.obligatoriodda.ClasesYEnums.Fachada;
import uy.ctc.edu.obligatoriodda.ClasesYEnums.Partida;
import uy.ctc.edu.obligatoriodda.ClasesYEnums.Jugador;
import uy.ctc.edu.obligatoriodda.ClasesYEnums.JugadorEnPartida;
import uy.ctc.edu.obligatoriodda.ClasesYEnums.SingletonJugadores;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Matias
 */
public class FrmLogin extends javax.swing.JFrame {

    private Fachada fachada = new Fachada();

    /**
     * Creates new form login
     */
    public FrmLogin() {
        initComponents();
        customizeUI();
    }

    /**
     * Customizes the UI to enhance visual appeal.
     */
    private void customizeUI() {
        // Set background color for the frame
        getContentPane().setBackground(new Color(240, 240, 255));

        // Style for labels
        jLabel1.setFont(new Font("Arial", Font.BOLD, 16));
        jLabel2.setFont(new Font("Arial", Font.BOLD, 16));

        // Style for text fields
        jNombreUsuario.setFont(new Font("Arial", Font.PLAIN, 14));
        jContrasenaUsuario.setFont(new Font("Arial", Font.PLAIN, 14));
        jNombreUsuario.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 255), 2));
        jContrasenaUsuario.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 255), 2));

        // Style for button
        jBtnEntrar.setFont(new Font("Arial", Font.BOLD, 14));
        jBtnEntrar.setBackground(new Color(100, 149, 237));
        jBtnEntrar.setForeground(Color.WHITE);
        jBtnEntrar.setFocusPainted(false);
        jBtnEntrar.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNombreUsuario = new javax.swing.JTextField();
        jBtnEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jContrasenaUsuario = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - ObligatorioDDA");

        jNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreUsuarioActionPerformed(evt);
            }
        });

        jBtnEntrar.setText("Entrar");
        jBtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEntrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Usuario:");
        jLabel2.setText("Contraseña:");

        jContrasenaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContrasenaUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNombreUsuario)
                    .addComponent(jContrasenaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jContrasenaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jBtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null); // Center the frame on the screen
    }// </editor-fold>//GEN-END:initComponents

    private void jNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreUsuarioActionPerformed

    private void jBtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEntrarActionPerformed
        // Login logic remains unchanged
        String usuarioIngresado = jNombreUsuario.getText();
        String contrasenaIngresada = new String(jContrasenaUsuario.getPassword());
        SingletonJugadores singleton = SingletonJugadores.getInstancia();

        Jugador jugadorLogueado = fachada.loginJugador(usuarioIngresado, contrasenaIngresada);

        if (jugadorLogueado.getNombreUsuario() != null) {
            Object[] resultado = fachada.ingresoPartida(jugadorLogueado);
            JugadorEnPartida jugadorPartida = (JugadorEnPartida) resultado[0];
            Partida partida = (Partida) resultado[1];
            String msg = "";
            String cod = "";
            if (resultado.length > 2 && resultado[2] != null) {
                msg = String.valueOf(resultado[2]);
            }
            if (resultado.length > 3 && resultado[3] != null) {
                cod = String.valueOf(resultado[3]);
            }

            if (jugadorPartida != null && partida != null && cod.equals("0")) {
                jNombreUsuario.setText("");
                jContrasenaUsuario.setText("");
                FrmJuego frm = new FrmJuego(partida, jugadorPartida);
                frm.setVisible(true);
            } else {
                new FrmAvisoLogin(msg).setVisible(true);
            }
        } else {
            String msg = "Nombre de usuario o contraseña incorrecta";
            new FrmAvisoLogin(msg).setVisible(true);
        }
    }//GEN-LAST:event_jBtnEntrarActionPerformed

    private void jContrasenaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContrasenaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContrasenaUsuarioActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new FrmLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEntrar;
    private javax.swing.JPasswordField jContrasenaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
